name:                hw1
version:             0.1.0.0
github:              "egormkn/haskell-course"
license:             MIT
author:              "Egor Makarenko"
maintainer:          "egormkn@yandex.ru"
copyright:           "2019 Egor Makarenko"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Haskell ITMO course at CTD, Task 1
category:            Learning Haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/egormkn/haskell-course>

dependencies:
- base >= 4.9 && < 5
- hspec

ghc-options:
- -Wall

library:
  source-dirs: src
  ghc-options:
  - -Werror

tests:
  hw1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hw1
    - hspec
    - hspec-discover
